#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;

my $USAGE = "Usage: $0 [-r <build root>] <file>\n";

my $buildroot = "";
GetOptions("r|root=s" => \$buildroot) or die $USAGE;
if (scalar(@ARGV) != 1) {
	die $USAGE;
}
if ($buildroot) {
	$buildroot .= "/";
}

my $fn = shift @ARGV;

system("fipshmac $buildroot$fn");

exit 0;
